# Copyright IBM Corp. 2026
# SPDX-License-Identifier: MPL-2.0

apiVersion: v2
name: boundary-worker
description: A Helm chart for HashiCorp Boundary Worker deployment
type: application
version: 0.1.0
appVersion: "1.0.0-ent"
keywords:
  - boundary
  - hashicorp
  - identity
  - access
  - security
  - zero-trust
  - worker
home: https://www.boundaryproject.io/
icon: https://raw.githubusercontent.com/hashicorp/boundary/main/boundary.png
sources:
  - https://github.com/hashicorp/boundary-worker-helm
maintainers:
  - name: HashiCorp
    url: https://github.com/hashicorp/boundary-worker-helm
