# Copyright IBM Corp. 2026

{{- if .Values.worker.persistence.recording.enabled }}
# Boundary Worker Recording PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "boundary.worker.recordingPvcName" . }}
  namespace: {{ include "boundary.namespace" . }}
  labels:
    {{- include "boundary.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
    storage-type: recording
spec:
  accessModes:
    - {{ .Values.worker.persistence.recording.accessMode }}
  {{- if .Values.worker.persistence.recording.storageClass }}
  storageClassName: {{ .Values.worker.persistence.recording.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.worker.persistence.recording.size }}
{{- end }}

{{- if and .Values.worker.persistence.recording.enabled .Values.worker.persistence.authStorage.enabled }}
---
{{- end }}
{{- if .Values.worker.persistence.authStorage.enabled }}
# Boundary Worker Auth Storage PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "boundary.worker.authStoragePvcName" . }}
  namespace: {{ include "boundary.namespace" . }}
  labels:
    {{- include "boundary.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
    storage-type: auth
spec:
  accessModes:
    - {{ .Values.worker.persistence.authStorage.accessMode }}
  {{- if .Values.worker.persistence.authStorage.storageClass }}
  storageClassName: {{ .Values.worker.persistence.authStorage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.worker.persistence.authStorage.size }}
{{- end }}