name: Release Pipeline

on:
  push:
    branches: [yash/actions]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        run: make ci-setup-helm

      - name: Setup Kubeconform
        run: make ci-setup-kubeconform

      - name: Run Helm Lint & Kubernetes Validation
        run: make ci-lint-helm-k8s

      - name: Upload rendered templates
        uses: actions/upload-artifact@v4
        with:
          name: rendered-templates
          path: rendered.yaml
          retention-days: 1

  lint-security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download rendered templates
        uses: actions/download-artifact@v4
        with:
          name: rendered-templates

      - name: Setup Trivy
        run: make ci-setup-trivy

      - name: Run Security Scan
        run: make ci-lint-security





  unit-test:
    name: lint
    needs: [lint-helm, lint-security]
    uses: ./.github/workflows/unit-test-job.yml

  acceptance-test:
    name: Acceptance Test
    needs: unit-test
    uses: ./.github/workflows/acceptance-test-job.yml

  release:
    name: Release
    needs: acceptance-test
    uses: ./.github/workflows/release-job.yml
