name: Release Pipeline

on:
  push:
    branches: [yash/actions]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        run: make setup-helm

      - name: Setup Kubeconform
        run: make setup-kubeconform

      - name: Run Helm Lint & Kubernetes Validation
        run: make lint-helm-k8s

      - name: Upload rendered templates
        uses: actions/upload-artifact@v4
        with:
          name: rendered-templates
          path: rendered.yaml
          retention-days: 1

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download rendered templates
        uses: actions/download-artifact@v4
        with:
          name: rendered-templates

      - name: Setup Trivy
        run: make setup-trivy

      # - name: Run Trivy Security Scan
      #   run: make trivy-scan

      - name: Setup Kubescape
        run: make setup-kubescape

      - name: Run Kubescape Security Scan
        run: make kubescape-scan

      - name: Upload Kubescape results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kubescape-results
          path: kubescape-output.json
          retention-days: 7





  unit-test:
    name: Unit Test
    needs: [lint, security]
    uses: ./.github/workflows/unit-test-job.yml

  acceptance-test:
    name: Acceptance Test
    needs: unit-test
    uses: ./.github/workflows/acceptance-test-job.yml

  release:
    name: Release
    needs: acceptance-test
    uses: ./.github/workflows/release-job.yml
